default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password:
  host: db

development:
  <<: *default
  database: hack2save_development

test:
  <<: *default
  database: hack2save_test
