default: &default
  adapter: postgresql
  encoding: utf8
  username:
  password:
  host: localhost
  port: 5432

development:
  <<: *default
  database: hack2save_development

test:
  <<: *default
  database: hack2save_test
